apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: digital-calculator-ingress
  namespace: calculation-prod
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-east-1:431412300010:certificate/40ff25b1-8b8f-46d9-a62b-e3e8d05f8a25
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
    alb.ingress.kubernetes.io/ssl-redirect: '443'
spec:
  ingressClassName: alb
  rules:
    - host: prassadhmulticloud.online
      http:
        paths:
          # Route backend API requests to the backend service
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: calc-backend-svc
                port:
                  number: 8080
          # Route everything else to the frontend service
          - path: /
            pathType: Prefix
            backend:
              service:
                name: calc-frontend-svc
                port:
                  number: 80
